input_list = [
    ('John studied a research paper slowly in the library yesterday.', 'John'),
    ('John studied a research paper slowly in the library yesterday.', 'library'),
    ('John studied a research paper slowly in the library yesterday.', 'yesterday'),
    ('Allen called David to ask about his homework.', 'Allen'),
    ('Allen called David to ask about his homework.', 'David'),
    ('Allen called David to ask about his homework.', 'homework'),
    ('A chemical element with the symbol He and atomic number 2 is Helium.', 'Helium'),
    ('Hangul was invented by King Sejong the Great in 1443 to write the Korean language.', 'Hangul'),
    ('Electronic music is music that employs electronic musical instruments, digital instruments and circuitry-based music technology.', 'Electronic music'),
    ('Sabah Bizi is an Albanian retired footballer who played for Vllaznia Shkodër and Partizani Tirana as well as the Albania national team.', 'Sabah Bizi'),
    ('Renazé is a commune in the Mayenne department in north-western France.', 'Renazé'),
    ('Smalls Jazz Club is a jazz club at 183 West 10th Street, Greenwich Village, New York City.', 'Smalls Jazz Club'),
    ('Dig is an American mystery/action-thriller miniseries that premiered on USA Network on March 5, 2015, and ran until May 7.', 'Dig'),
    ('Oskar Birger Ferdinand Stenman (23 December 1925 in Solna, Sweden — 20 May 1970 in Hägersten, Sweden) was a Swedish footballer who played as a midfielder.', 'Oskar Birger Ferdinand Stenman'),
    ("The Jorgensen's General Store is a historic site in Grant-Valkaria, Florida.", "Jorgensen's General Store"),
    ('Myrmecia flavicoma is an ant species native to Australia.', "Myrmecia flavicoma"),
    ('The Roman Catholic Diocese of Elbląg (Latin: Elbingen(sis)) is a diocese located in the city of Elbląg in the Ecclesiastical province of Warmia in Poland.', 'Roman Catholic Diocese of Elbląg'),
    ('Lucio Parrillo is an artist, known for comic books, role-playing game covers, and Magic: The Gathering cards.', 'Lucio Parrillo'),
    ('Patsuia is a butterfly genus of the Limenitidinae subfamily.', 'Patsuia'),
    ('Enrique Colla was an Argentine football player.', 'Enrique Colla'),
    ("Caroline Ann O'Connor  (born 2 September 1962) is a Helpmann Award-winning, Olivier Award-nominated Anglo-Australian singer, dancer and actress (theatre, film, TV).", "Caroline Ann O'Connor"),
    ('Harry George Tate (18 July 1862 – 9 March 1949) was an English cricketer who played one first-class cricket match for Somerset in 1882.', 'Harry George Tate'),
    ('Hirokazu Kore-eda (是枝 裕和, Koreeda Hirokazu, born 6 June 1962) is a Japanese film director, producer, screenwriter, and editor.', 'Hirokazu Kore-eda'),
    ('Coronaviruses are a group of related RNA viruses that cause diseases in mammals and birds.', 'mammals and birds')
]